name: TypeScript Check

on:
  push:
    branches: [ main, develop, 'feature/**', 'story/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run TypeScript compiler check
      run: npx tsc --noEmit

    - name: Check for TypeScript errors in tests
      run: npx tsc --noEmit --project tsconfig.app.json

    - name: Generate TypeScript coverage report
      if: matrix.node-version == '20.x'
      run: |
        echo "TypeScript check completed successfully ✅" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Files Checked" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        find src -name "*.ts" -o -name "*.tsx" | wc -l | xargs echo "Total TypeScript files:">> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
